#!/bin/sh

echo "Setting up Attack Folder..."
ectf-attack-init . || exit 1
echo "Set up Attack Folder: Success"

echo "Building team design..."
ectf-build-design || exit 1
echo "Build Team Design: Success"
